# Generated by Django 4.0.4 on 2022-05-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='belongs_to',
            new_name='user',
        ),
    ]
